package com.paotuitui.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import lombok.Data;

@Data
public class Audit implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit.id
     *
     * @mbg.generated Tue Jul 30 15:43:44 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit.student_id
     *
     * @mbg.generated Tue Jul 30 15:43:44 CST 2024
     */
    private Long studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit.status
     *
     * @mbg.generated Tue Jul 30 15:43:44 CST 2024
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit.img_str
     *
     * @mbg.generated Tue Jul 30 15:43:44 CST 2024
     */
    private String imgStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table audit
     *
     * @mbg.generated Tue Jul 30 15:43:44 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit
     *
     * @mbg.generated Tue Jul 30 15:43:44 CST 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", studentId=").append(studentId);
        sb.append(", status=").append(status);
        sb.append(", imgStr=").append(imgStr);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit
     *
     * @mbg.generated Tue Jul 30 15:43:44 CST 2024
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Audit other = (Audit) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getStudentId() == null ? other.getStudentId() == null : this.getStudentId().equals(other.getStudentId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getImgStr() == null ? other.getImgStr() == null : this.getImgStr().equals(other.getImgStr()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit
     *
     * @mbg.generated Tue Jul 30 15:43:44 CST 2024
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getStudentId() == null) ? 0 : getStudentId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getImgStr() == null) ? 0 : getImgStr().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit
     *
     * @mbg.generated Tue Jul 30 15:43:44 CST 2024
     */
    public static Audit.Builder builder() {
        return new Audit.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table audit
     *
     * @mbg.generated Tue Jul 30 15:43:44 CST 2024
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table audit
         *
         * @mbg.generated Tue Jul 30 15:43:44 CST 2024
         */
        private Audit obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table audit
         *
         * @mbg.generated Tue Jul 30 15:43:44 CST 2024
         */
        public Builder() {
            this.obj = new Audit();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column audit.id
         *
         * @param id the value for audit.id
         *
         * @mbg.generated Tue Jul 30 15:43:44 CST 2024
         */
        public Builder id(Integer id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column audit.student_id
         *
         * @param studentId the value for audit.student_id
         *
         * @mbg.generated Tue Jul 30 15:43:44 CST 2024
         */
        public Builder studentId(Long studentId) {
            obj.setStudentId(studentId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column audit.status
         *
         * @param status the value for audit.status
         *
         * @mbg.generated Tue Jul 30 15:43:44 CST 2024
         */
        public Builder status(Integer status) {
            obj.setStatus(status);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column audit.img_str
         *
         * @param imgStr the value for audit.img_str
         *
         * @mbg.generated Tue Jul 30 15:43:44 CST 2024
         */
        public Builder imgStr(String imgStr) {
            obj.setImgStr(imgStr);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table audit
         *
         * @mbg.generated Tue Jul 30 15:43:44 CST 2024
         */
        public Audit build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table audit
     *
     * @mbg.generated Tue Jul 30 15:43:44 CST 2024
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        studentId("student_id", "studentId", "BIGINT", false),
        status("status", "status", "TINYINT", false),
        imgStr("img_str", "imgStr", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table audit
         *
         * @mbg.generated Tue Jul 30 15:43:44 CST 2024
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table audit
         *
         * @mbg.generated Tue Jul 30 15:43:44 CST 2024
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table audit
         *
         * @mbg.generated Tue Jul 30 15:43:44 CST 2024
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table audit
         *
         * @mbg.generated Tue Jul 30 15:43:44 CST 2024
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table audit
         *
         * @mbg.generated Tue Jul 30 15:43:44 CST 2024
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table audit
         *
         * @mbg.generated Tue Jul 30 15:43:44 CST 2024
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table audit
         *
         * @mbg.generated Tue Jul 30 15:43:44 CST 2024
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table audit
         *
         * @mbg.generated Tue Jul 30 15:43:44 CST 2024
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table audit
         *
         * @mbg.generated Tue Jul 30 15:43:44 CST 2024
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table audit
         *
         * @mbg.generated Tue Jul 30 15:43:44 CST 2024
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table audit
         *
         * @mbg.generated Tue Jul 30 15:43:44 CST 2024
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table audit
         *
         * @mbg.generated Tue Jul 30 15:43:44 CST 2024
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table audit
         *
         * @mbg.generated Tue Jul 30 15:43:44 CST 2024
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table audit
         *
         * @mbg.generated Tue Jul 30 15:43:44 CST 2024
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table audit
         *
         * @mbg.generated Tue Jul 30 15:43:44 CST 2024
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table audit
         *
         * @mbg.generated Tue Jul 30 15:43:44 CST 2024
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table audit
         *
         * @mbg.generated Tue Jul 30 15:43:44 CST 2024
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}