package com.paotuitui.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import lombok.Data;

@Data
public class Student implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbg.generated Tue Jul 30 16:18:38 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_id
     *
     * @mbg.generated Tue Jul 30 16:18:38 CST 2024
     */
    private Long studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.phone_number
     *
     * @mbg.generated Tue Jul 30 16:18:38 CST 2024
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.auth_state
     *
     * @mbg.generated Tue Jul 30 16:18:38 CST 2024
     */
    private Integer authState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbg.generated Tue Jul 30 16:18:38 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Jul 30 16:18:38 CST 2024
     */
    public static Student.Builder builder() {
        return new Student.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student
     *
     * @mbg.generated Tue Jul 30 16:18:38 CST 2024
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table student
         *
         * @mbg.generated Tue Jul 30 16:18:38 CST 2024
         */
        private Student obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table student
         *
         * @mbg.generated Tue Jul 30 16:18:38 CST 2024
         */
        public Builder() {
            this.obj = new Student();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column student.id
         *
         * @param id the value for student.id
         *
         * @mbg.generated Tue Jul 30 16:18:38 CST 2024
         */
        public Builder id(Long id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column student.student_id
         *
         * @param studentId the value for student.student_id
         *
         * @mbg.generated Tue Jul 30 16:18:38 CST 2024
         */
        public Builder studentId(Long studentId) {
            obj.setStudentId(studentId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column student.phone_number
         *
         * @param phoneNumber the value for student.phone_number
         *
         * @mbg.generated Tue Jul 30 16:18:38 CST 2024
         */
        public Builder phoneNumber(String phoneNumber) {
            obj.setPhoneNumber(phoneNumber);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column student.auth_state
         *
         * @param authState the value for student.auth_state
         *
         * @mbg.generated Tue Jul 30 16:18:38 CST 2024
         */
        public Builder authState(Integer authState) {
            obj.setAuthState(authState);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table student
         *
         * @mbg.generated Tue Jul 30 16:18:38 CST 2024
         */
        public Student build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table student
     *
     * @mbg.generated Tue Jul 30 16:18:38 CST 2024
     */
    public enum Column {
        id("id", "id", "BIGINT", false),
        studentId("student_id", "studentId", "BIGINT", false),
        phoneNumber("phone_number", "phoneNumber", "VARCHAR", false),
        authState("auth_state", "authState", "TINYINT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table student
         *
         * @mbg.generated Tue Jul 30 16:18:38 CST 2024
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table student
         *
         * @mbg.generated Tue Jul 30 16:18:38 CST 2024
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table student
         *
         * @mbg.generated Tue Jul 30 16:18:38 CST 2024
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table student
         *
         * @mbg.generated Tue Jul 30 16:18:38 CST 2024
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table student
         *
         * @mbg.generated Tue Jul 30 16:18:38 CST 2024
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table student
         *
         * @mbg.generated Tue Jul 30 16:18:38 CST 2024
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table student
         *
         * @mbg.generated Tue Jul 30 16:18:38 CST 2024
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table student
         *
         * @mbg.generated Tue Jul 30 16:18:38 CST 2024
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table student
         *
         * @mbg.generated Tue Jul 30 16:18:38 CST 2024
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table student
         *
         * @mbg.generated Tue Jul 30 16:18:38 CST 2024
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table student
         *
         * @mbg.generated Tue Jul 30 16:18:38 CST 2024
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table student
         *
         * @mbg.generated Tue Jul 30 16:18:38 CST 2024
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table student
         *
         * @mbg.generated Tue Jul 30 16:18:38 CST 2024
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table student
         *
         * @mbg.generated Tue Jul 30 16:18:38 CST 2024
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table student
         *
         * @mbg.generated Tue Jul 30 16:18:38 CST 2024
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table student
         *
         * @mbg.generated Tue Jul 30 16:18:38 CST 2024
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table student
         *
         * @mbg.generated Tue Jul 30 16:18:38 CST 2024
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}